kind = "web"
previewPath = "/"
title = "Unnao Teachers' Premier League 2026"
version = "1.0.0"
id = "artifacts/utpl"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23226

[services.development]
run = "pnpm run dev"

[services.production]
build = [ "pnpm", "run", "build" ]
publicDir = "dist"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23226"
